name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: "https://lapras.com/public/GS4EVTV"
          ICON_FIRST: "#03102f"
          ICON_SECOND: "#1688bf"
          BACKGROUND_FIRST: "#53c5f8"
          BACKGROUND_SECOND: "#00579b"
          LANG: "en"
          # 以下オプション
          # https://lapras-card-generator.vercel.app でカスタマイズしたデザインを設定可能
          # ICON_FIRST: "#030E21"
          # ICON_SECOND: "#1688BF"
          # BACKGROUND_FIRST: "#020E27"
          # BACKGROUND_SECOND: "#0E5593"
          # LANG: "ja"
          # CARD_WIDTH: "400"
          # UPDATE_TIME: "true"
          # README_FILE: "README.md"
          # IS_CENTER: "true"
          # ALTERNATIVE_TEXT: "Score of {SHARE_ID} on LAPRAS"
